### ISSUE TITLE
cannot load such file -- dynamoid/adapter/aws (LoadError)

### ISSUE THREAD

**Issue by MakeApps** [Veraticus/Dynamoid#103]
Followed all the step  but I'm getting following error

/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13.rc1/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- dynamoid/adapter/aws (LoadError)

```
from /.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13.rc1/lib/active_support/dependencies.rb:251:in `block in require'
from /.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.13.rc1/lib/active_support/dependencies.rb:236:in `load_dependency'
```

**Comment by Alua-Kinzhebayeva** [comment]
Hi, @MakeApps! How did you get around config.adapter = 'aws_sdk' line

**Comment by MakeApps** [comment]
I think its only config.adapter = 'aws_sdk' or config.adapter = 'AWS_SDK', can't remember correctly. Please try.

**Comment by Alua-Kinzhebayeva** [comment]
@MakeApps , I appreciate your reply. In the current version of the most developed fork it is turned out to be 'aws_sdk_2'
