### ISSUE TITLE
Deprecate this gem officially

### ISSUE THREAD

**Issue by hlms** [Veraticus/Dynamoid#188]
It would be great if the library can be declared deprecated officially. Here are the reasons:

1. NO querying support based on index: It requires key field to be named “id” which is **not** the case with most of the tables. Issue link: https://github.com/Veraticus/Dynamoid/issues/132

2. NO querying support based on Global Secondary Index (GSI): GSI was introduced on AWS SDK v2, whereas dynamoid is using AWS SDK v1. Link: https://github.com/Veraticus/Dynamoid#prerequisities

3. The latest commit is on Dec 21, 2013 and looks like the library will soon be deprecated officially. 

People should better use Ruby AWS SDK v2 directly.
I figured out the above issues after ending up using the dynamoid for my project.
I wish other people would **not** face the same issues I faced.

If the library is **not** planned to be deprecated, kindly ...
1. move the dynamoid to AWS SDK v2.
2. Resolve the issues: https://github.com/Veraticus/Dynamoid/issues

**Comment by zitooon** [comment]
+1

**Comment by ishita2310** [comment]
+1

**Comment by ngordon17** [comment]
+1

**Comment by loganb** [comment]
Will take it under consideration. Let's see how this year plays out.
